### ISSUE TITLE
Adjust reporting form for this campaign

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/common-voice-global-sprint#6]
I'll give this a go and do a PoC.

**Comment by mikehenrty** [comment]
Here are the things we need to collect in the form:
 * email address (required)
 * free text input for sentences (optional) (do we have a max char count for this?)
 * link to source of sentences (optional)
 * language of sentences (required)
 * checkbox to say "I certify that I either created these sentences, or got them from a public domain source"

Then, on this form, we will need something that says:
"If you have too many sentences to paste into this form, please email mikey@mozilla.com"

**Comment by MichaelKohler** [comment]
What do you think about adding a (+) icon and then having an input field per sentence? Then we can automatically create a "sentence" entry in the data source for each of the fields. Also, what languages should be selectable? Or are we ok with free text and then somehow map it (warning: people will enter it in their own script or localized language versions, not English)

**Comment by mikehenrty** [comment]
> What do you think about adding a (+) icon and then having an input field per sentence?

I would rather not ask for a single sentence at a time, but allow people to copy and paste multiple sentences. The reason is, less friction, less clips. I can imagine people composing these sentences in a text editor or copy&pasting from some other doc, and I want to make it simple to do a bulk paste.

> Also, what languages should be selectable? Or are we ok with free text and then somehow map it (warning: people will enter it in their own script or localized language versions, not English)

Free text input is fine, as we will have to manually copy this stuff over anyway.
